# Generated by Django 3.0.3 on 2020-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(default='TBD', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URI_text', models.CharField(max_length=200)),
                ('user_choice', models.CharField(default='TBD', max_length=200)),
                ('comment', models.CharField(default='TBD', max_length=400)),
            ],
        ),
    ]
