# Generated by Django 3.0.3 on 2020-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='URI_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='left_URI_text',
            field=models.CharField(default='left', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='right_URI_text',
            field=models.CharField(default='right', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='user_decision',
            field=models.CharField(default='TBD', max_length=200),
        ),
    ]
