# Generated by Django 3.1.4 on 2021-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0002_auto_20200810_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='left_URI_text_triply',
            field=models.CharField(default='left', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='right_URI_text_triply',
            field=models.CharField(default='right', max_length=200),
        ),
    ]
