# Generated by Django 3.0.3 on 2020-06-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URI',
            new_name='Entry',
        ),
    ]
