# Generated by Django 3.0.3 on 2020-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_auto_20200621_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user_choice',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
